/**
 * Public YouTube links used by the site.
 * Prefer linking the original video + timestamp over publishing full transcripts.
 * Public project references: https://shaul.vercel.app and https://davar.bible.
 *
 * Channels only:
 * - Eric de Jesús Rodríguez Mendoza
 * - Natanael Doldan · Somos el Cuerpo del Mesías
 */

export const sourceLinks = {
  // Eric de Jesús
  benHaAdam: "https://www.youtube.com/watch?v=-I1zqJZ8hQM",
  benHaAdamCielo: "https://www.youtube.com/watch?v=-I1zqJZ8hQM&t=147s",
  benHaAdamProfetas: "https://www.youtube.com/watch?v=-W2giXMqvUE&t=1240s",
  benHaAdamPortador: "https://www.youtube.com/watch?v=-W2giXMqvUE&t=2747s",
  benHaAdamAnciano: "https://www.youtube.com/watch?v=-W2giXMqvUE&t=2884s",
  deidadParte2: "https://www.youtube.com/watch?v=L_6X4-WsETE",
  semilla: "https://www.youtube.com/watch?v=L_6X4-WsETE&t=3264s",
  vientre: "https://www.youtube.com/watch?v=L_6X4-WsETE&t=3724s",
  sangre: "https://www.youtube.com/watch?v=L_6X4-WsETE&t=4414s",
  corporeidadIncorruptible: "https://www.youtube.com/watch?v=L_6X4-WsETE&t=3968s",
  deidadParte4: "https://www.youtube.com/watch?v=3ehqAOSaahA",
  yojananCuerpo: "https://www.youtube.com/watch?v=-W2giXMqvUE",
  yojananSangre: "https://www.youtube.com/watch?v=csFssLdcLsE&t=3574s",
  sangreVidaBiologica: "https://www.youtube.com/watch?v=aRt3PuB_gSw&t=2449s",
  corporeidadMarcos: "https://www.youtube.com/watch?v=j52NQB6sKSQ",
  corporeidadYojanan: "https://www.youtube.com/watch?v=2C6YJnz5fKs",
  nombre: "https://www.youtube.com/watch?v=lTV1Im2d5QI",
  deidad: "https://www.youtube.com/watch?v=DOUwTpLXTY4",
  elohimAhavah: "https://www.youtube.com/watch?v=DOUwTpLXTY4&t=411s",
  kyrios: "https://www.youtube.com/watch?v=zaeuqpePDmc&t=315s",
  carneMarcos: "https://www.youtube.com/watch?v=j52NQB6sKSQ&t=2955s",
  carneYojanan: "https://www.youtube.com/watch?v=2C6YJnz5fKs&t=127s",
  meymra: "https://www.youtube.com/watch?v=1MoxwBR4bg4",
  meymraTargum: "https://www.youtube.com/watch?v=ahPoKpA9F7o&t=1860s",
  meymraCorporea: "https://www.youtube.com/watch?v=1MoxwBR4bg4&t=4750s",
  apocalipsis: "https://www.youtube.com/watch?v=AoCqV_Yel5Y",
  apocalipsisIntroduccion: "https://www.youtube.com/watch?v=cgb42eKnbJw&t=458s",
  apocalipsisVision: "https://www.youtube.com/watch?v=f-7YFaoUCrs&t=300s",
  filadelfia: "https://www.youtube.com/watch?v=VzUpWkv8BCQ&t=1624s",
  dosTestigos: "https://www.youtube.com/watch?v=T6Sn9-djsC4",
  isaiasIntro: "https://www.youtube.com/watch?v=SrmxQo97ptE",
  isaiasIntro2: "https://www.youtube.com/watch?v=HgqgVFSqhmY",
  isaias56: "https://www.youtube.com/watch?v=HgqgVFSqhmY&t=3735s",
  tefilah: "https://www.youtube.com/watch?v=k2V_xN81ozU&t=1182s",
  temploMayor: "https://www.youtube.com/watch?v=f3tHvC2IgWo&t=1314s",
  pactoAbraham: "https://www.youtube.com/watch?v=IzbgqzNwD4k&t=813s",
  galatas: "https://www.youtube.com/watch?v=fP1kJg1oQAo",
  romanos: "https://www.youtube.com/watch?v=zLynBpmjJr0",
  romanos11: "https://www.youtube.com/watch?v=MHLbizeZrPc",
  ruaj: "https://www.youtube.com/watch?v=p0hF7k-ZtRc",
  ruajRomanos: "https://www.youtube.com/watch?v=9RtvJSFxMyA",
  abaYojanan10puerta: "https://www.youtube.com/watch?v=8geNmTcW6ZI",
  abaYojanan10obras: "https://www.youtube.com/watch?v=-5nbvwGrEDY",
  abaYojanan14: "https://www.youtube.com/watch?v=2oGHEpfFPlM",
  yojanan17: "https://www.youtube.com/watch?v=o6rOivQHyU4",
  abaMagnificencia: "https://www.youtube.com/watch?v=kVAJOj4wkR0",
  abaDeidad: "https://www.youtube.com/watch?v=DOUwTpLXTY4",
  abaOracion: "https://www.youtube.com/watch?v=3mikRgwy-xw",
  tribunalCelestial: "https://www.youtube.com/watch?v=4nYEkCmDn14",
  tribunalCelestial2: "https://www.youtube.com/watch?v=LfJ1LGjOXho",
  nicolaismoEfeso: "https://www.youtube.com/watch?v=MgPCTRyjtGo",
  nicolaismoPergamo: "https://www.youtube.com/watch?v=D56MVOVBDaY",
  nicolaismoLiderazgo: "https://www.youtube.com/watch?v=FEuQ3220iwk",

  // Natanael Doldan · Somos el Cuerpo del Mesías
  reemplazo1: "https://www.youtube.com/watch?v=iDuvm4VTAJg",
  reemplazo2: "https://www.youtube.com/watch?v=jAmhhsLJil8",
  trinidad: "https://www.youtube.com/watch?v=sHZ5OdsU1vo",
  trinidadShema: "https://www.youtube.com/watch?v=sHZ5OdsU1vo&t=756s",
  abolicionLey: "https://www.youtube.com/watch?v=goTCEVpn-20",
  abolicionLeyTorah: "https://www.youtube.com/watch?v=goTCEVpn-20&t=549s",
  natanaelBajoLey: "https://www.youtube.com/watch?v=9QEm8tTuoRM",
  natanaelLeyAbolida: "https://www.youtube.com/watch?v=DGN2OzGfgvU",
  neoidolatria: "https://www.youtube.com/watch?v=jvZU0tznR84",
  natanaelRomanos7: "https://www.youtube.com/watch?v=LMFB3e6HPMA",
  natanaelGalatasJudaizacion: "https://www.youtube.com/watch?v=QxG0zi25Wgg",
  natanaelGalatasTorahOral: "https://www.youtube.com/watch?v=OIHTZpk3h8E",
  natanaelGalatasGracia: "https://www.youtube.com/watch?v=wvW-2nLnKj8",
  natanaelGalatasEmunah: "https://www.youtube.com/watch?v=b-ZqoEl_9fA",
  natanaelGalatasSentencia: "https://www.youtube.com/watch?v=O3PzUB3Il_k",
  natanaelGalatasRuaj: "https://www.youtube.com/watch?v=fR6qkxt9hrQ",
  natanaelIsaias19Primera: "https://www.youtube.com/watch?v=1JCBJOGpRRM&t=5s",
  natanaelIsaias19Segunda: "https://www.youtube.com/watch?v=TndqALEl76U"
};

export const sourceCatalog = [
  ["Juan (Yojanán) 10: puerta, pastor y Abá", "Eric de Jesús · Abá como fuente de la promesa", sourceLinks.abaYojanan10puerta, "Disponible"],
  ["Juan (Yojanán) 10: Abá, obras y morada", "Eric de Jesús · obras de Abá y morada", sourceLinks.abaYojanan10obras, "Disponible"],
  ["Juan (Yojanán) 14: Abá, Menajem y el Nombre", "Eric de Jesús · Abá no aparte del Mesías", sourceLinks.abaYojanan14, "Disponible"],
  ["Juan (Yojanán) 17: manifestar el Nombre", "Evangelio según Juan (Yojanán), parte 64", sourceLinks.yojanan17, "Disponible"],
  ["La magnificencia del Mesías", "Efesios 3 · Abá y la manifestación", sourceLinks.abaMagnificencia, "Disponible"],
  ["Deidad del Mesías · Abá", "Eric de Jesús · Elohim y Abá", sourceLinks.abaDeidad, "Disponible"],
  ["Tribunal celestial y verbos de oración", "Eric de Jesús · proseuchomai / lehitpallel", sourceLinks.tribunalCelestial, "Disponible"],
  ["Oración y confesión ante el cielo", "Eric de Jesús · continuidad del tribunal", sourceLinks.tribunalCelestial2, "Disponible"],
  ["Santísima trinidad", "Somos el Cuerpo del Mesías · Natanael Doldan", sourceLinks.trinidad, "Disponible"],
  ["Teología del reemplazo (1)", "Somos el Cuerpo del Mesías · Natanael Doldan", sourceLinks.reemplazo1, "Disponible"],
  ["Teología del reemplazo (2)", "Somos el Cuerpo del Mesías · Natanael Doldan", sourceLinks.reemplazo2, "Disponible"],
  ["Romanos 11 · el olivo e Israel", "La carta a los romanos, parte 26 · Eric de Jesús", sourceLinks.romanos11, "Disponible"],
  ["Abolición de la ley", "Somos el Cuerpo del Mesías · Natanael Doldan", sourceLinks.abolicionLey, "Disponible"],
  ["¿Qué es estar bajo la ley?", "Somos el Cuerpo del Mesías · Natanael Doldan", sourceLinks.natanaelBajoLey, "Disponible"],
  ["¿La ley está abolida?", "Somos el Cuerpo del Mesías · Natanael Doldan", sourceLinks.natanaelLeyAbolida, "Disponible"],
  ["La ley de Elohim y la ley del pecado · Romanos 7", "Somos el Cuerpo del Mesías · Natanael Doldan", sourceLinks.natanaelRomanos7, "Disponible"],
  ["Gálatas · La judaización en el pueblo", "Somos el Cuerpo del Mesías · Natanael Doldan", sourceLinks.natanaelGalatasJudaizacion, "Disponible"],
  ["Gálatas · Torah escrita y Torah oral", "Somos el Cuerpo del Mesías · Natanael Doldan", sourceLinks.natanaelGalatasTorahOral, "Disponible"],
  ["Gálatas · La Torah dada por gracia", "Somos el Cuerpo del Mesías · Natanael Doldan", sourceLinks.natanaelGalatasGracia, "Disponible"],
  ["Gálatas · La escucha de la emunah", "Somos el Cuerpo del Mesías · Natanael Doldan", sourceLinks.natanaelGalatasEmunah, "Disponible"],
  ["Gálatas · Estábamos bajo sentencia", "Somos el Cuerpo del Mesías · Natanael Doldan", sourceLinks.natanaelGalatasSentencia, "Disponible"],
  ["Gálatas · El Ruaj es opuesto a la carne", "Somos el Cuerpo del Mesías · Natanael Doldan", sourceLinks.natanaelGalatasRuaj, "Disponible"],
  ["Isaías (Yeshaiáhu) 19 · Carga judicial de Mitzráim", "Libro de Isaías (Yeshaiáhu) · capítulo 19", sourceLinks.natanaelIsaias19Primera, "Pendiente de cotejo"],
  ["Isaías (Yeshaiáhu) 19 · Mitzráim conocerá a Elohim", "Libro de Isaías (Yeshaiáhu) · capítulo 19", sourceLinks.natanaelIsaias19Segunda, "Pendiente de cotejo"],
  ["Isaías (Yeshaiáhu) 56 · justicia y casa de oración", "Isaías (Yeshaiáhu), parte 2 · Eric de Jesús", sourceLinks.isaias56, "Disponible · segmento con timestamp"],
  ["Tefilah · oración, juicio y sumisión", "Efesios, parte 5 · Eric de Jesús", sourceLinks.tefilah, "Disponible · segmento con timestamp"],
  ["Yehoshúa · mayor que el Templo", "Eric de Jesús · Jag Hashavu'ot 5781", sourceLinks.temploMayor, "Disponible · segmento con timestamp"],
  ["Pacto de Avraham · multitud de naciones", "Eric de Jesús · Parashat Bejuqotay", sourceLinks.pactoAbraham, "Disponible · segmento con timestamp"],
  ["Elohim es Rúaj", "Evangelio según Juan (Yojanán), parte 12 · Eric de Jesús", sourceLinks.ruaj, "Disponible"],
  ["El Rúaj de Elohim y del hombre", "Romanos, parte 18 · Eric de Jesús", sourceLinks.ruajRomanos, "Disponible"],
  ["Apocalipsis (Sodot) · mensaje a Éfeso", "La revelación de Yehoshúa HaMashíaj, parte 5 · Eric de Jesús", sourceLinks.nicolaismoEfeso, "Disponible"],
  ["Apocalipsis (Sodot) · mensaje a Pérgamo", "La revelación de Yehoshúa HaMashíaj, parte 7 · Eric de Jesús", sourceLinks.nicolaismoPergamo, "Disponible"],
  ["Neoidolatría", "Somos el Cuerpo del Mesías · Natanael Doldan", sourceLinks.neoidolatria, "Disponible"],
  ["Ben HaAdam y Ben HaElohim", "El Evangelio según Juan (Yojanán), parte 9 · Eric de Jesús", sourceLinks.benHaAdam, "Disponible"],
  ["Ben HaAdam · cuerpo del cielo", "El Evangelio según Juan (Yojanán), parte 9 · segmento con timestamp", sourceLinks.benHaAdamCielo, "Disponible · segmento con timestamp"],
  ["Ben HaAdam · Torah y Profetas", "El Evangelio según Juan (Yojanán), parte 28 · segmento con timestamp", sourceLinks.benHaAdamProfetas, "Disponible · segmento con timestamp"],
  ["Ben HaAdam · el portador del Adam de arriba", "El Evangelio según Juan (Yojanán), parte 28 · segmento con timestamp", sourceLinks.benHaAdamPortador, "Disponible · segmento con timestamp"],
  ["Ben HaAdam · Anciano de días", "El Evangelio según Juan (Yojanán), parte 28 · segmento con timestamp", sourceLinks.benHaAdamAnciano, "Disponible · segmento con timestamp"],
  ["El Adam del cielo y la semilla", "La deidad del Mesías, parte 2 · Eric de Jesús", sourceLinks.deidadParte2, "Disponible"],
  ["Corporeidad incorruptible", "La deidad del Mesías, parte 2 · segmento sobre cuerpo y alimentos", sourceLinks.corporeidadIncorruptible, "Disponible · segmento con timestamp"],
  ["Corporeidad y origen del Mesías", "La deidad del Mesías, parte 4 · Eric de Jesús", sourceLinks.deidadParte4, "Disponible"],
  ["Sangre y vida biológica del Mesías", "Evangelio según Juan (Yojanán), parte 42 · segmento sobre la vida derramada", sourceLinks.sangreVidaBiologica, "Disponible · segmento con timestamp"],
  ["La deidad del Mesías: Elohim y Abá", "Serie de deidad · Eric de Jesús", sourceLinks.deidad, "Disponible"],
  ["Elohim · atributos y amor entrañable", "La deidad del Mesías, parte 3 · Eric de Jesús", sourceLinks.elohimAhavah, "Disponible · segmento con timestamp"],
  ["Kyrios y el Nombre de cuatro letras", "Evangelio según Marcos (Markos), parte 38 · Eric de Jesús", sourceLinks.kyrios, "Disponible · segmento con timestamp"],
  ["Carne, cuerpo y naturaleza del Mesías", "Evangelio según Marcos (Markos), parte 12 · Eric de Jesús", sourceLinks.carneMarcos, "Disponible · segmento con timestamp"],
  ["Carne en el Evangelio según Juan (Yojanán)", "Juan (Yojanán), parte 5 · Eric de Jesús", sourceLinks.carneYojanan, "Disponible · segmento con timestamp"],
  ["Arjé, Logos y Meymra", "El Evangelio según Juan (Yojanán), parte 2 · Eric de Jesús", sourceLinks.meymra, "Disponible"],
  ["Meymra y los antropomorfismos del Targum", "Parashat Génesis (Bereshit) · Eric de Jesús", sourceLinks.meymraTargum, "Disponible · segmento con timestamp"],
  ["Meymra como expresión corpórea", "Juan (Yojanán), parte 2 · Eric de Jesús", sourceLinks.meymraCorporea, "Disponible · segmento con timestamp"],
  ["Apocalipsis (Sodot) 1: contexto", "La revelación de Yehoshúa HaMashíaj · Eric de Jesús", sourceLinks.apocalipsis, "Disponible"],
  ["Apocalipsis (Sodot) 1: revelación de Yehoshúa", "La revelación de Yehoshúa HaMashíaj · presentación e introducción", sourceLinks.apocalipsisIntroduccion, "Disponible · segmento con timestamp"],
  ["Apocalipsis (Sodot): visiones y Ben Ha’Adam", "La revelación de Yehoshúa HaMashíaj · visión del Hijo del Hombre", sourceLinks.apocalipsisVision, "Disponible · segmento con timestamp"],
  ["Apocalipsis (Sodot) · mensaje a Filadelfia", "La revelación de Yehoshúa HaMashíaj, parte 10 · mensaje a Filadelfia", sourceLinks.filadelfia, "Disponible · segmento con timestamp"],
  ["Dos testigos y nombres espirituales", "Sedom y Mitzráim · Eric de Jesús", sourceLinks.dosTestigos, "Disponible"],
  ["Isaías (Yeshaiáhu) · Introducción y sujeto profético", "Isaías (Yeshaiáhu), parte 2 · Eric de Jesús", sourceLinks.isaiasIntro2, "Disponible"],
  ["Gálatas: qué significa judaizar", "Gálatas · Eric de Jesús", sourceLinks.galatas, "Disponible"],
  ["Romanos", "Romanos · Eric de Jesús", sourceLinks.romanos, "Disponible"]
];
